// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhutyyvmzfogmpnrmxgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJodXR5eXZtemZvZ21wbnJteGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjE5NDgsImV4cCI6MjA3MjgzNzk0OH0.j84k-4DP28fysdPln7s_a4b518w3rvhtRWYg6j_kYog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});